H: 512
W: 512
batch_size: auto
data_path: data/car-turn
device: cuda
guidance_scale: 7.5
latents_path: latents
max_batch_size: 400
max_kv_size: 10
n_frames: all
n_inversion_steps: 50
n_timesteps: 50
negative_prompt: ugly, blurry, low res, unrealistic, unaesthetic
output_path: results
pnp_attn_t: 0.8
pnp_f_t: 0.8
prompt: "A red SUV on a mountainous journey."
sd_version: '2.1'
seed: 1
similarity_mean_threshold: 0.75
similarity_region_threshold: 0.6
